NestedMenu/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from menu.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view()),
    path('index', IndexView.as_view()),
    path('menu/', include("menu.urls")),

]

menu/urls.py
from django.urls import path, include
from .views import MenuView

app_name = "menu"
urlpatterns = [
    path('', MenuView.as_view(), name='main'),
    path('<str:p>', MenuView.as_view()),
    path('<str:p>/<str:p1>', MenuView.as_view()),
    path('<str:p>/<str:p1>/<str:p2>', MenuView.as_view()),
    path('<str:p>/<str:p1>/<str:p2>/<str:p3>', MenuView.as_view()),
    path('<str:p>/<str:p1>/<str:p2>/<str:p3>/<str:p4>', MenuView.as_view())
]

menu/models.py
from django.db import models


class MenuName(models.Model):
    name = models.CharField("Наименование меню", max_length=255, unique=True)

    class Meta:
        verbose_name = 'Наименование меню'
        verbose_name_plural = 'Наименование меню'
        db_table = "menu_menu_name"

    def __str__(self):
        return self.name


class Menu(models.Model):
    label = models.CharField("Метка", max_length=255)
    url = models.CharField("Ссылка", max_length=255)
    menu = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE, related_name='submenu', verbose_name='принадлежит пункту меню')
    menu_name = models.ForeignKey(MenuName, on_delete=models.CASCADE, verbose_name='наименование меню')

    class Meta:
        verbose_name = 'Меню'
        verbose_name_plural = 'Меню'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        # При попытке сохранить в подменю самого себя или подменю которое принадлежит другому имени меню,
        if (self.id is not None and self.id == self.menu_id) \
                or (self.menu is not None and self.menu_name != self.menu.menu_name):
        # if self.id is not None and self.id == self.menu_id:
            # сохранение надо отменить.
            return
        super().save(force_insert, force_update, using, update_fields)
        self.related_item_menu_name_save(self)

    def related_item_menu_name_save(self, item: 'Menu'):
        """ При сохранении меню проверят, если у принадлежащих ему подменю не совпадает Имя меню со своим,
            то меняет всем подменю и под-подменю Имя меню на такое же, как и у него.
         """
        submenu = item.submenu.all()
        if len(submenu) != 0 and submenu[0].menu_name != item.menu_name:
            item.submenu.update(menu_name=item.menu_name)
            for item in item.submenu.all():
                self.related_item_menu_name_save(item)

    def __str__(self):
        return f"{self.menu_name}: {self.label} - {self.url}"

menu/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "index.html"


class MenuView(TemplateView):
    template_name = "menu/menu_page.html"

menu/templates/menu/fragments/generate_menu.html
<ul>
    {% for item in menu  %}

        {% if 'current_item' in item %}
            <li>
                <span>{{ item.label }}</span>
            </li>
            {% if 'items' in item %}
                <ul>
                    {% for submenu in item.items %}
                        <li>
                            <a href="{{ submenu.url }}">
                                {{ submenu.label }}
                                {% if 'items' in submenu %}->{% endif %}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% elif item.is_show %}
            <li>
                <a href="{{ item.url }}">
                    {{ item.label }}
                    {% if 'items' in item and not item.items.0.is_show %}->{% endif %}
                </a>
            </li>
        {% endif %}

        {% if 'items' in item %}
            {% include 'menu/fragments/generate_menu.html' with menu=item.items %}
        {% endif %}
    {% endfor %}
</ul>

menu/templates/menu/fragments/nested_menu.html
{% if error %}
    <h2>Ошибка</h2>
    <p>Меню <b>{{ menu_name }}</b> не найдено</p>
{% else %}
    <h2>Меню: {{ menu_name }}</h2>
    {% include 'menu/fragments/generate_menu.html' %}
{% endif %}

menu/templates/menu/menu_page.html
{% extends 'base.html' %}

{% block title %} Вложенное меню {% endblock %}

{% load draw_menu %}

{% block content %}
<div>
{% draw_menu 'menu_1' %}
</div>
<div>
{% draw_menu 'menu_2' %}
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ru-RU">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %} Вложенное меню {% endblock %}

{% load draw_menu %}

{% block content %}
    <h2><a href="{% url 'menu:main' %}">Меню</a></h2>

{% endblock %}